import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class Info {
    public static List list = new ArrayList();

        public static HashMap<Integer, String> numberRom = new HashMap<>();

    public static void info() {
            list.add(null);
            list.add("I");
            list.add("II");
            list.add("III");
            list.add("IV");
            list.add("V");
            list.add("VI");
            list.add("VII");
            list.add("VIII");
            list.add("IX");
            list.add("X");

            numberRom.put(0, "");
            numberRom.put(1, "I");
            numberRom.put(2, "II");
            numberRom.put(3, "III");
            numberRom.put(4, "IV");
            numberRom.put(5, "V");
            numberRom.put(6, "VI");
            numberRom.put(7, "VII");
            numberRom.put(8, "VIII");
            numberRom.put(9, "IX");
            numberRom.put(10, "X");
            numberRom.put(11, "XI");
            numberRom.put(12, "XII");
            numberRom.put(13, "XIII");
            numberRom.put(14, "XIV");
            numberRom.put(15, "XV");
            numberRom.put(16, "XVI");
            numberRom.put(17, "XVII");
            numberRom.put(18, "XVIII");
            numberRom.put(19, "XIX");
            numberRom.put(20, "XX");
            numberRom.put(21, "XXI");
            numberRom.put(22, "XXII");
            numberRom.put(23, "XXIII");
            numberRom.put(24, "XXIV");
            numberRom.put(25, "XXV");
            numberRom.put(26, "XXVI");
            numberRom.put(27, "XXVII");
            numberRom.put(28, "XXVIII");
            numberRom.put(29, "XXIX");
            numberRom.put(30, "XXX");
            numberRom.put(31, "XXXI");
            numberRom.put(32, "XXXII");
            numberRom.put(33, "XXXIII");
            numberRom.put(34, "XXXIV");
            numberRom.put(35, "XXXV");
            numberRom.put(36, "XXXVI");
            numberRom.put(37, "XXXVII");
            numberRom.put(38, "XXXVIII");
            numberRom.put(39, "XXXIX");
            numberRom.put(40, "XL");
            numberRom.put(41, "XLI");
            numberRom.put(42, "XLII");
            numberRom.put(43, "XLIII");
            numberRom.put(44, "XLIV");
            numberRom.put(45, "XLV");
            numberRom.put(46, "XLVI");
            numberRom.put(47, "XLVII");
            numberRom.put(48, "XLVIII");
            numberRom.put(49, "XLIX");
            numberRom.put(50, "L");
            numberRom.put(51, "LI");
            numberRom.put(52, "LII");
            numberRom.put(53, "LIII");
            numberRom.put(54, "LIV");
            numberRom.put(55, "LV");
            numberRom.put(56, "LVI");
            numberRom.put(57, "LVII");
            numberRom.put(58, "LVIII");
            numberRom.put(59, "LIX");
            numberRom.put(60, "LX");
            numberRom.put(61, "LXI");
            numberRom.put(62, "LXII");
            numberRom.put(63, "LXIII");
            numberRom.put(64, "LXIV");
            numberRom.put(65, "LXV");
            numberRom.put(66, "LXVI");
            numberRom.put(67, "LXVII");
            numberRom.put(68, "LXIII");
            numberRom.put(69, "LXIX");
            numberRom.put(70, "LXX");
            numberRom.put(71, "LXXI");
            numberRom.put(72, "LXXII");
            numberRom.put(73, "LXXIII");
            numberRom.put(74, "LXXIV");
            numberRom.put(75, "LXXV");
            numberRom.put(76, "LXXVI");
            numberRom.put(77, "LXXVII");
            numberRom.put(78, "LXXVIII");
            numberRom.put(79, "LXXIX");
            numberRom.put(80, "LXXX");
            numberRom.put(81, "LXXXI");
            numberRom.put(90, "CX");
            numberRom.put(100, "C");

}}
